# Generated by Django 2.1.4 on 2019-01-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_pointtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtracking',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge'),
            preserve_default=False,
        ),
    ]
