# Generated by Django 2.1.4 on 2019-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_pointtracking_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringitem',
            old_name='points',
            new_name='max_points',
        ),
        migrations.AddField(
            model_name='scoringitem',
            name='min_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
