# Generated by Django 2.1.4 on 2019-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20190104_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='09A0D3', max_length=10),
            preserve_default=False,
        ),
    ]
